# Generated by Django 6.0.7 on 2026-07-28 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('muscle_worked', models.CharField(blank=True, max_length=100, null=True)),
                ('exercise_type', models.CharField(default='reps', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('current_xp', models.IntegerField(default=0)),
                ('next_level_xp', models.IntegerField(default=300)),
                ('current_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('attributes', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemorizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(default='in_progress', max_length=30)),
                ('current_verse', models.IntegerField(default=0)),
                ('total_verses', models.IntegerField(default=0)),
                ('last_practiced', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorization_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=1)),
                ('reps', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('is_weighted', models.BooleanField(default=False)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.workoutexercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('xp_earned', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.workoutsession'),
        ),
        migrations.CreateModel(
            name='DhikrLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dhikr_type', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('target_count', models.IntegerField(default=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhikr_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'dhikr_type')},
            },
        ),
        migrations.CreateModel(
            name='SalahLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fajr', models.CharField(default='pending', max_length=20)),
                ('dhuhr', models.CharField(default='pending', max_length=20)),
                ('asr', models.CharField(default='pending', max_length=20)),
                ('maghrib', models.CharField(default='pending', max_length=20)),
                ('isha', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salah_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
