# Generated by Django 6.0.7 on 2026-07-28 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='session',
        ),
        migrations.RenameField(
            model_name='characterprofile',
            old_name='last_activity_date',
            new_name='last_workout_date',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='category',
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='total_hours_trained',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='total_workouts_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='average_rpe',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='plan_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='plan_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='session_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='total_reps_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='total_sets_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='total_volume_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(max_length=100)),
                ('exercise_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_muscle', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.workoutsession')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.IntegerField(default=1)),
                ('reps', models.IntegerField(default=0)),
                ('weight_kg', models.FloatField(default=0.0)),
                ('duration_sec', models.IntegerField(default=0)),
                ('set_type', models.CharField(default='working', max_length=20)),
                ('rpe', models.IntegerField(blank=True, null=True)),
                ('estimated_1rm', models.FloatField(default=0.0)),
                ('rest_seconds_after', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.sessionexercise')),
            ],
        ),
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
