# Generated by Django 4.2.30 on 2026-08-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sleeplog_unique_together_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='monthly_payment',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='paid_from_savings',
        ),
        migrations.AddField(
            model_name='debt',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='debt',
            name='source',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
