# Generated by Django 4.2.30 on 2026-08-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_debt_due_date_remove_debt_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='source',
        ),
        migrations.AddField(
            model_name='debt',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='interest_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='debt',
            name='monthly_payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='debt',
            name='paid_from_savings',
            field=models.BooleanField(default=False),
        ),
    ]
