# Generated by Django 4.2.30 on 2026-08-19 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_debt_currency_remove_debt_source_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debt',
        ),
    ]
