# Generated by Django 4.2.30 on 2026-08-04 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_achievementrecord_id_alter_adhkarlog_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salahlog',
            unique_together={('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='sleeplog',
            unique_together={('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='weightlog',
            unique_together={('date',)},
        ),
        migrations.AlterField(
            model_name='achievementrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adhkarlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhkar_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='callreminder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cyclelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dhikrlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dhikr_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthnote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorizationentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorization_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorizationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorization_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='missedfast',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missed_fasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfumeformula',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfume_formulas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfumeversion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfume_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quranreadinglog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quran_reading_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='revisionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salahlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salah_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingsentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wealthprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wealth_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='xpevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
