# Generated by Django 4.2.30 on 2026-08-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_salahlog_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='total_volume_kg',
        ),
    ]
